### PR TITLE
Change of API Simics-21363

### PR DESCRIPTION
**Pull request by perwolde**
CORE_write_configuration_persistent to
       SIM_write_configuration_state

### CODE REVIEW

**Review by mandolaerik — COMMENTED** [review]
Jira reference in commit message should be uppercase SIMICS. Otherwise good.

**Comment by syssimics** [comment]
Verification [#12625900](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12625900): fail

**Comment by mandolaerik** [comment]
I started pretests against 6 and 7. Should it be built with some other base branch?

**Comment by syssimics** [comment]
Verification [#12644693](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12644693): pass

**Comment by mandolaerik** [comment]
The verification build against 6 passed, which is the important part. The 7 side is covered by your pretest.

Please merge this PR first, this should auto-update the 6 branch. You can then merge that submodule update to 7.

**Review by mandolaerik — APPROVED** [review]

**Pull request merged**
