### PR TITLE
Disable part of test on Windows

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9784323

**Comment by mandolaerik** [comment]
windows: https://teamcity01-ir.devtools.intel.com/buildConfiguration/SimicsCiSimics_MonoTargets_fLW/9784331

**Review by lwaern-intel — APPROVED** [review]

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9784322

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9784331

**Pull request merged**
