### PR TITLE
Use the new 6-only macro to reduce duplication

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by mandolaerik** [comment]
Depends on https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/5354

**Review by andreashedstrom-intel — APPROVED** [review]

**Comment by mandolaerik** [comment]
[V 6](https://teamcity01-ir.devtools.intel.com/viewQueued.html?itemId=12562286)
[V 7](https://teamcity01-ir.devtools.intel.com/viewQueued.html?itemId=12562555)

**Comment by syssimics** [comment]
Verification [#12562286](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12562286): pass

**Comment by syssimics** [comment]
Verification [#12562555](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12562555): pass

**Pull request merged**
