### PR TITLE
Lost and found patches

### PR DESCRIPTION
**Pull request by mandolaerik**
- Improve logging test
- Mention that sizeoftype does not count as a constant
- Move topsort to module traits
- Refactor: Move method sorting to traits.py
- Improve how irrelevant porting messages are presented.

### CODE REVIEW

**Comment by syssimics** [comment]
TeamCity build completed (FAILURE): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9553519

**Review by JonatanWaern — APPROVED** [review]
I only skimmed the method sorting -> traits commit (assuming its almost only code moves)
Looks good to me otherwise

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9558260

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9560345

**Pull request merged**
