### PR TITLE
Provide initiator in bank instrumentation

### PR DESCRIPTION
**Pull request by jhbaarnh**

### CODE REVIEW

**Comment by jhbaarnh** [comment]
This must not be merged before https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/1527

**Comment by syssimics** [comment]
DML [#9851486](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9851486): fail

**Comment by mandolaerik** [comment]
Started a failing test to mark this PR as blocked; will restart when #1527 is merged.

**Review by mandolaerik — APPROVED** [review]
Looks good

**Comment by syssimics** [comment]
Verification [#9851485](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9851485): fail

**Comment by syssimics** [comment]
DML [#9861704](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9861704): fail

**Comment by syssimics** [comment]
Verification [#9861670](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9861670): fail

**Comment by syssimics** [comment]
DML [#9861770](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9861770): fail

**Comment by syssimics** [comment]
DML [#9861813](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9861813): fail

**Comment by syssimics** [comment]
Verification [#9861769](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9861769): fail

**Comment by syssimics** [comment]
Verification [#9861812](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9861812): pass

**Pull request merged**
