### PR TITLE
Add repo-local spelling passlist

### PR DESCRIPTION
**Pull request by mandolaerik**
This is used by the spell checker when built as a submodule of the
Simics base repo.

### CODE REVIEW

**Comment by mandolaerik** [comment]
prerequisite for https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/3531

**Comment by mandolaerik** [comment]
It is expected that t300 complains that the new passlist contains misspelled words; this is silenced in https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/3531

**Comment by syssimics** [comment]
Verification [#11266558](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=11266558): fail

**Comment by syssimics** [comment]
Verification [#11266605](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=11266605): fail

**Comment by syssimics** [comment]
Verification [#11266658](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=11266658): fail

**Pull request merged**
