### PR TITLE
Update docs for signal_port and signal_connect

### PR DESCRIPTION
**Pull request by MagnusIntel**
In the documentation, these were described in the midst of "Templates for reset"

### CODE REVIEW

**Comment by mandolaerik** [comment]
We have a section [5.4 Connect related templates](https://simics-download.pdx.intel.com/simics-6/docs/html/dml-1.4-reference-manual/utility.html#connect-related-templates), I suppose we should move the `signal_connect` template there, or alternatively rethink the categories.

Docs are extracted in order, so moving around docs requires moving around the corresponding code, which is OK.

**Comment by MagnusIntel** [comment]
> We have a section [5.4 Connect related templates](https://simics-download.pdx.intel.com/simics-6/docs/html/dml-1.4-reference-manual/utility.html#connect-related-templates), I suppose we should move the `signal_connect` template there, or alternatively rethink the categories.
> 
> Docs are extracted in order, so moving around docs requires moving around the corresponding code, which is OK.

Can I put signal_port under "Connect related templates" as well? It fits better there than the current place in any case

**Comment by mandolaerik** [comment]
Having a separate one for signals makes sense, but perhaps signal should come before reset (which is based on signal)?

**Comment by MagnusIntel** [comment]
Can we just get this in and then debate new sections etc? The current state is awful and this PR should be a distinct improvement

**Pull request merged**
