### PR TITLE
Update bug references

### PR DESCRIPTION
**Pull request by pshishpo-intel**
Update references for bugs that were migrated to Jira.

JFYI, the update was done in a semiatomated way with the help of the following script:
```
#!/bin/bash

# format: "<Bugzilla bug number> <JIRA record number>":
data=(
"21873 9502"
"21900 9504"
...
)

for d in "${data[@]}"; do
    set -- $d
    echo "${1} -> ${2}"
    git grep --recurse-submodules -l "bug ${1}" | xargs sed -i "s/bug ${1}/SIMICS-${2}/g"
done
```

### CODE REVIEW

**Comment by pshishpo-intel** [comment]
@mandolaerik Could you please review this pull request?

**Review by mandolaerik — APPROVED** [review]
We also have some bugzilla numbers in filenames, `test/bugs/T_*.dml`. Can be fixed in a separate PR.

**Comment by lwaern-intel** [comment]
This is incredibly helpful. Thanks for going through the effort to do this!

**Review by lwaern-intel — APPROVED** [review]

**Comment by pshishpo-intel** [comment]
> We also have some bugzilla numbers in filenames, `test/bugs/T_*.dml`. Can be fixed in a separate PR.

Likely. Not all bug from Bugzilla were transferred to Jira.

**Comment by pshishpo-intel** [comment]
> This is incredibly helpful. Thanks for going through the effort to do this!

@lwaern-intel you are welcome! Can you also merge the pull request? For me Github says:
```This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
```

**Pull request merged**
