### PR TITLE
Make `explicit_param_decls` stable

### PR DESCRIPTION
**Pull request by lwaern-intel**
I want this in in time for SQPFU.

### CODE REVIEW

**Comment by syssimics** [comment]
Verification [#13774908](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13774908): ✅ pass

**Review by mandolaerik — APPROVED** [review]
Two remarks, no need to fix:
* "grammatically" in a commit msg
* we could consider an ESYNTAX test for `param x :;`

**Comment by lwaern-intel** [comment]
> * we could consider an ESYNTAX test for `param x :;`

It'd be a bit of an odd-duck as it's forbidden _grammatically_, as in it'd be a parse error. We don't typically have tests for those.

**Comment by syssimics** [comment]
Verification [#13782576](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13782576): ✅ pass

**Pull request merged**
