### PR TITLE
Have line directive resets use absolute path -- SIMICS-22848

### PR DESCRIPTION
**Pull request by lwaern-intel**

### CODE REVIEW

**Comment by syssimics** [comment]
Verification [#14057998](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14057998): ✅ pass

**Review by mandolaerik — APPROVED** [review]

**Comment by syssimics** [comment]
Verification [#14059501](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14059501): ❌ fail

**Comment by syssimics** [comment]
Verification [#14059794](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14059794): ❌ fail

**Comment by syssimics** [comment]
Verification [#14060050](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14060050): ❌ fail

**Comment by syssimics** [comment]
Verification [#14060737](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14060737): ❌ fail

**Comment by syssimics** [comment]
Verification [#14060923](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14060923): ✅ pass

**Pull request merged**
