### PR TITLE
Remove invalid release markers

### PR DESCRIPTION
**Pull request by aconradi**

### CODE REVIEW

**Comment by JonatanWaern** [comment]
A little confused by this change, probably some RC convo I've missed;
- what makes this release 'invalid'?
- what actually happens when you remove an old release marker in the middle like this?

**Comment by aconradi** [comment]
> A little confused by this change, probably some RC convo I've missed;
> 
>     * what makes this release 'invalid'?

There is no release with that number in that time frame. Someone did a mistake. Please note that this release is marked as 6138, while the surrounding ones are 63xx.

> 
>     * what actually happens when you remove an old release marker in the middle like this?

Nothing, except you avoid the query for release-notes stumbling on this unexpected release marker.

**Review by JonatanWaern — APPROVED** [review]
Dont know

**Review by lwaern-intel — APPROVED** [review]
Thanks. By-the-by, I appreciate the upcoming change so that useless release markers will no longer be added, they make rebasing a pain ;)

**Pull request merged**
