### PR TITLE
Generate refman title page for github wiki

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by mandolaerik** [comment]
See https://github.com/intel/device-modeling-language/wiki/DML-1.4-Reference-Manual
The idea is to have a first page that the "Home" page can link to

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9565203

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9565202

**Review by lwaern-intel — APPROVED** [review]
Looks good in code, though not sure how good it will look when rendered. We'll see.

**Pull request merged**
