### PR TITLE
Provide byte order information in register_view for DML 1.4

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9554522

**Comment by mandolaerik** [comment]
Apart from "unit" testing, I also did some smoke testing to see that it works in practice:
* migrated test-device to DML 1.4
* ran `t40/s-device-reg-*`, *without* these patches, pass
* rebuilt test-device and reran `t40/s-device-reg-*`, with these patches applied, pass
* rebuilt test-device and reran `t40/s-device-reg-*`, with these patches applied but logic inverted (`_le_byte_order = byte_order != "little-endian"`), fail

**Comment by syssimics** [comment]
TeamCity build completed (FAILURE): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9560588

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9560648

**Review by JonatanWaern — COMMENTED** [review]
Is there a particular reason we are not re-using the testing style of previous register-view tests? (we are also duplicating some stuff from those tests here I think)

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9568674

**Comment by mandolaerik** [comment]
> Is there a particular reason we are not re-using the testing style of previous register-view tests?

Just confusion from my side. The test is indeed completely redundant, now removed.

Note that now that after this one and #33 we no longer rely on .xml files. This means we can make the 1.4 reginfo tests normal tests, named `T_*`.

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9568673

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9568730

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9568729

**Review by JonatanWaern — APPROVED** [review]

**Pull request merged**
