### PR TITLE
`connect.set_attribute`: Suppress Coverity event `var_deref_model`

### PR DESCRIPTION
**Pull request by lwaern-intel**

### CODE REVIEW

**Review by mandolaerik — APPROVED** [review]
Approved if you can verify that it solves the problem.

**Comment by syssimics** [comment]
Verification [#12468534](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12468534): pass

**Comment by lwaern-intel** [comment]
Forcibly merging to allow release tomorrow. @mandolaerik if you can think of a better solution we'll discuss it on R.C.

**Comment by syssimics** [comment]
Verification [#12469065](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=12469065): pass

**Pull request merged**
