### PR TITLE
Only load pre-parsed files that end with .dmlast

### PR DESCRIPTION
**Pull request by mandolaerik**
- **Only load pre-parsed files that end with .dmlast**

### CODE REVIEW

**Review by lwaern-intel — APPROVED** [review]
Incredible.

**Comment by mandolaerik** [comment]
[W fast](https://teamcity01-ir.devtools.intel.com/viewQueued.html?itemId=14064716&tab=queuedBuildOverviewTab)

**Comment by syssimics** [comment]
Verification [#14064698](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14064698): ✅ pass

**Comment by mandolaerik** [comment]
[W fast](https://teamcity01-ir.devtools.intel.com/viewQueued.html?itemId=14065752)

**Comment by syssimics** [comment]
Verification [#14065746](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=14065746): ❌ fail

**Pull request merged**
