### PR TITLE
Remove RELEASENOTES.docu files

### PR DESCRIPTION
**Pull request by aconradi**
They are no longer used after the move to Markdown based release-notes.

### CODE REVIEW

**Review by mandolaerik — APPROVED** [review]
Looks good (but a test build is needed). I trust that you verified that none of the docu files has recently added notes.

**Comment by syssimics** [comment]
Verification [#13711926](http://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13711926): ✅ pass

**Comment by aconradi** [comment]
What is holding up merging this? I can't merge it myself.

**Review by lwaern-intel — APPROVED** [review]
Nothing.

**Pull request merged**
