### PR TITLE
Add support for `log warning`

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by mandolaerik** [comment]
Depends on https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/6062 , will start tests once that one is merged.

**Comment by syssimics** [comment]
Verification [#13033564](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13033564): fail

**Comment by syssimics** [comment]
Verification [#13034164](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13034164): fail

**Comment by syssimics** [comment]
Verification [#13036277](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13036277): pass

**Review by lwaern-intel — APPROVED** [review]
I've held off on reviewing this so you could get the kerfuffle of how to approach `SIM_LOG_WARNING` in 6 settled, but it seems it has been for like a month. Approved if so.

**Pull request merged**
