### PR TITLE
Add support for pypy as interpreter

### PR DESCRIPTION
**Pull request by mandolaerik**
- Remove run-time dependency on simicsutils
- Check explicitly for utf8_mode

### CODE REVIEW

**Comment by mandolaerik** [comment]
t126 passes when run manually with `pypy3 -X utf8` as interpreter

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9645184

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9645166

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9645183

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9645780

**Comment by syssimics** [comment]
TeamCity build completed (SUCCESS): https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=9645779

**Review by lwaern-intel — APPROVED** [review]
Simple enough, `env.py` was the only thing I had questions about.

**Pull request merged**
