### PR TITLE
Avoid test failure on systems where stack is unlimited by default

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by mandolaerik** [comment]
[Test L SLES15](https://teamcity01-ir.devtools.intel.com/viewQueued.html?itemId=13398636)

**Comment by syssimics** [comment]
Verification [#13398624](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13398624): pass

**Comment by syssimics** [comment]
Verification [#13398631](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=13398631): pass

**Review by andreashedstrom-intel — APPROVED** [review]
I assume this works, it sure works on then SLES15 build you triggered. Thanks.

**Pull request merged**
