### PR TITLE
Adapt to new package-spec format

### PR DESCRIPTION
**Pull request by mandolaerik**

### CODE REVIEW

**Comment by syssimics** [comment]
Verification [#11726520](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=11726520): fail

**Comment by syssimics** [comment]
Verification [#11779955](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=11779955): pass

**Comment by syssimics** [comment]
Verification [#11780067](https://teamcity01-ir.devtools.intel.com/viewLog.html?buildId=11780067): pass

**Review by lwaern-intel — APPROVED** [review]
Approved assuming you've made sure this is sufficient for https://github.com/intel-innersource/applications.simulators.simics.simics-base/pull/4090.

**Pull request merged**
